const ChatActionTypes = {
  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
  CLEAR_HISTORY: 'CLEAR_HISTORY',
  RESET_CHAT_STATE: 'RESET_CHAT_STATE',
  SET_CHAT_BLOCKED: 'SET_CHAT_BLOCKED',
  SET_CHAT_AVAILABLE: 'SET_CHAT_AVAILABLE',
};

export default ChatActionTypes;